### ISSUE TITLE
Any verbose support option?

### ISSUE THREAD

**Issue by joao64** [whoek/scrumdog-binaries#1]
Hi, really appreciated your work!

I'm trying it pointing to a jira server setup. All seems going fine, no error is printed out, sqllite db is created  and apparently the query is fine (in the jira project there are thousands issues, the same query on the browser returns results).
 
![Capture](https://user-images.githubusercontent.com/10669342/186846336-954b0a94-4b25-4a30-930b-122a2446f963.JPG)

But examining the db, it is empty.  Maybe version api and json results differs from the one expected by scrumdog.
Just wondering whether could be possible add a "verbose" option for printing out all the "curl" requests and responses for helping debugging.

Thanks in advance, have a nice day.
Giovanni

**Comment by whoek** [comment]
Hello Giovanni -- Many Thanks for trying it out.

Appear that call to JIRA is not working.   Does transaction `curl` work on the command line?

**1 - LOG files / verbose**

There should be a `log` folder in the main directory. The full response of the last `curl` call should be in there.  If it works OK -- there should be at least 3 files related to the `get fields` call.
```
response_zz_issues_code.txt
response_zz_fields_header.txt
response_zz_fields_body.json

       where zz is the value of the [db_table_prefix] tag in setup file.
```
The header.txt file only contains the response code -- 200 being OK.

Lets know if these files were created.  If not -- I will add more log entries so that we can see where it get stuck.

**2 - Please also check that your URL is listed OK.  Here is my setup file -- with email / API masked**

```

[server]   https://site12345.atlassian.net/
[email]    zzzzz@zzz.com
[api_token]    xxxxxxxxxxxxxxxxxxxxxxxxxxx
[db_filename]   jira.db
[db_table_prefix]  zz
[jql]              project = zz

[fields]

assignee   assignee.displayName
creator    creator.displayName
issuetype  issuetype.name
priority   priority.name
project    project.key
reporter   reporter.displayName
status     status.name
votes      votes.votes
watches_count        watches.watchCount
aggregate_progress   aggregateprogress.progress
aggregate_total      aggregateprogress.total
parent_key           parent.key
progress             progress.progress
progress_total       progress.total
comments_total       comment.total
comments_all         comment.comments

```
You may want to email me your setup file -- with email and API token masked.

**3 - More LOG file entries**

In the meantime I will add more log-file entries so we can see where it get stuck.

Kind Regards
Willem

**Comment by joao64** [comment]
Hello WIllem, thanks for your detailed feedback!

Here are some additional info - looking at the content of the log files, I guess that the problem is more related on our site setup rather than your code :)

Anyway:

**1 LOG** 
The log files were created - the header file is here (changed hostname):


`Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Set-Cookie: GCLB=COeK2a2M2J3IVw; path=/; HttpOnly
Via: 1.1 google
Date: Fri, 26 Aug 2022 07:18:45 GMT
Transfer-Encoding: chunked
Content-Type: text/html;charset=UTF-8
X-Authentication-Denied-Reason: CAPTCHA_CHALLENGE; login-url=https://mysite.com/login.jsp
X-ASESSIONID: 1rrr477
WWW-Authenticate: OAuth realm="https%3A%2F%2Fmysite.com"
X-Seraph-LoginReason: AUTHENTICATION_DENIED
Set-Cookie: JSESSIONID=3AF......A4EA; Max-Age=86400; Expires=Sat, 27-Aug-2022 07:18:45 GMT; Path=/; Secure; HttpOnly; SameSite=None
Strict-Transport-Security: max-age=31536000
Content-Security-Policy: frame-ancestors 'self'
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: strict-origin-when-cross-origin
X-ANODEID: jira-service-sq78
X-AREQUESTID: 438x1983968x1
`

while the body json file is 
`  <html>
<head>
    <title>Forbidden (403)</title>....`

**2 Config file**

`[server]   https://mysite.com
[email] me@mysite.com
[api_token] NjczMT.......SfkRe4Fj0
[db_filename]   jira.db
[db_table_prefix]      SWM 
[jql] project = SWM`


Although it is missing the fields setup (as in yours) - it seems that the problem happens before the access to the api at authentication level, or rest path url

**API invocation**

I was able to use our jira apis by invoking them from an  AppsScript script, with these settings (just reported here only to check if the curl invocation in scrumdog is somehow similar):

`const JIRAISSUE = "https://mysite.com/rest/api/2/issue";
const MYJIRATOKEN = "NjczMT.......SfkRe4Fj0":
...
 var myData = {
      "fields": {
        "project": { "key": project },
        "summary": summary,
        "description": summary,
        "parent": { "key": issueParent },
        "components": [{ "name": component }],
        "issuetype": { "id": typeId }
      }
    };
  // adding options to the API call, including headers and basic authorization
  var urlCallHeaders = {
    'Authorization': 'Bearer '.concat(MYJIRATOKEN),
    'Content-type': 'application/json'
  };

  var urlCallOptions = {
    'headers': urlCallHeaders,
    'method': 'post',
    'muteHttpExceptions': false,
    'payload': JSON.stringify(myData)
  };

var response = UrlFetchApp.fetch(JIRAISSUE, urlCallOptions);`


Thank in advance for the time - I was hoping to use Scrumdog for querying the issues via Sqllite (a great approach!) - but I think our setup has some peculiarity of its own.

Cordially, CIao
Giovanni

**Comment by whoek** [comment]
Giovanni -- 
If you don't mind -- I am trying a few other options

Just to confirm -- not that it matter -- but are you using the Windows, Mac or Linux version?  _Looking at he screenshot -- it appears to be Windows.._

What I will do is to add the Jira (curl) request info being used to the logfile -- so that it can be run manually in order to debug.

I am on the move today ... so will do it tomorrow morning and report back when a new version is available.
Many Thanks again for trying it -- much appreciated.

Willem

**Comment by whoek** [comment]
Hello Giovanni --

Scrumdog make use of `curl` in the background to pull data from Jira.  The two Jira API calls being used for issues are:     
1) first a GET to pull the Issue fields     
2) followed by one or more POST calls to get the Issue data

**GET FIELDS**

The curl command used by the program to pull back list of all the issue fields .  

```
curl "-si" "-X" "GET" "-H" "Accept: application/json" "https://xxx.atlassian.net/rest/api/3/field" "--user" "yyy@yyy.com:zzz"

where:
xxx is your domain
yyy@yyy.com is your user ID
zzz is your API token

```
This should work if executed in the command line.   On your side -- it is failing on this call, before it even get to pulling the issue data. 

**GET ISSUES**

The curl command being used to get the issues

```
curl "-si" "-X" "POST" "-H" "Accept: application/json" "-H" "Content-Type: application/json" "https://xxx.atlassian.net//rest/api/3/search" "--data-binary" "@-" "--user" "yyy@yyy.com:zzz"

```

Input data:
```
{
"jql": "project = zz",
"maxResults": 1000,
"fields": ["*all"],
"fieldsByKeys": false,
"startAt": 100
}

```
This can be tested in command line by    
1) Save input data above in a text file -- e.g. `input.txt`    
2) Changing `"@-"` to `"@input.txt"` in the curl command listed above


JIRA references
- Issue fields:   https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-fields/#api-group-issue-fields
- Issue search:  https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-group-issue-search


Thanks,
Willem

**Comment by joao64** [comment]
Hello Willem, here I am again. Thank you very much for the references and for the kind explanation!

I did some tests using the curl settings you kindly provided. 

* I tried getting the fields using the api rest. In our setup, api v.2 is active  (https://mysite.com/rest/api/2/field), v3 not.
* Trying accessing with curl .... "--user" "me@mysite.com:<tokenhere>"  I am redirected to a login page (error 403: authentication faijlure: reason: authentication_denies).
* BUT if try with `curl "-si" "-X" "GET" "-H" "Accept: application/json" "Authorization: Bearer <tokenhere> https://mysite.com/rest/api/2/field`   without the user option all goes well and I get the json with the results.


Wanted to share results with you.

Thanks, have a nice day
/gio

**Comment by whoek** [comment]
Gio --

Thanks again for taking the time to respond.
Interesting!  I suspect your Jira account type is different to mine.
I have been using it on a JIRA Cloud account.

1 - Fields API
I changed the API in scrumdog to use the v2 API -- as it is similar as v3.
Latest version uploaded to download page.

2 - JIRA Issues API
For now I have to stick to the v3 of API as it include the Issue comments - which is not included in v2.
In v2 of API the comments is a separate API call.

For now I am closing the call due scrumdog not using v2 of JIRA Issue API.
If any changes -- I will let you know.

Kind Regards,
Willem
