### ISSUE TITLE
Mac OS will not run .exe files

### ISSUE THREAD

**Issue by the1337beauty** [whoek/scrumdog-binaries#2]
For the OSX-Intel binaries, you have `scrumdog.exe` which Mac OS recognizes as a Windows executable file and will not open it. I attempted to run the file in the Linux folder but I'm getting an error `zsh: exec format error: ./scrumdog`

**Comment by whoek** [comment]
Thanks.  I will follow up.

**Comment by whoek** [comment]
@the1337beauty   I have compiled and uploaded a new version of  `scrumdog` -- the latest downloads are available from [here](https://github.com/whoek/scrumdog-binaries/tree/main).  Lets know if any issues.  Many Thanks
